spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route2
          uri: https://www.google.com
          predicates:
            - Query=url,google
